import { NextRequest, NextResponse } from "next/server";
import fs from "node:fs/promises";
import path from "node:path";
import JSZip from "jszip";
import { createClient } from "@supabase/supabase-js";

export const runtime = "nodejs";

const INCLUDE_PATHS = [
  "app",
  "components",
  "lib",
  "public",
  "package.json",
  "package-lock.json",
  "tsconfig.json",
  "next.config.ts",
  "postcss.config.mjs",
  "eslint.config.mjs",
  "next-env.d.ts",
  "README.md",
] as const;

const SKIP_DIRS = new Set([
  ".git",
  ".next",
  "node_modules",
  ".turbo",
  "coverage",
  "dist",
  "build",
]);

const SKIP_EXTS = new Set([
  ".log",
  ".tmp",
  ".temp",
  ".DS_Store",
]);

const SKIP_FILE_NAMES = new Set([
  ".env",
  ".env.local",
  ".env.production",
  ".env.development",
]);

function getEnv(name: string) {
  const value = process.env[name];
  if (!value) {
    throw new Error(`${name} 환경변수가 필요합니다.`);
  }
  return value;
}

async function exists(target: string) {
  try {
    await fs.access(target);
    return true;
  } catch {
    return false;
  }
}

async function addPathToZip(zip: JSZip, baseDir: string, relPath: string) {
  const absPath = path.join(baseDir, relPath);
  const stat = await fs.stat(absPath);

  if (stat.isDirectory()) {
    const dirName = path.basename(absPath);
    if (SKIP_DIRS.has(dirName)) return;

    const entries = await fs.readdir(absPath, { withFileTypes: true });
    for (const entry of entries) {
      const nextRel = path.join(relPath, entry.name);
      if (entry.isDirectory()) {
        if (SKIP_DIRS.has(entry.name)) continue;
        await addPathToZip(zip, baseDir, nextRel);
      } else {
        if (SKIP_FILE_NAMES.has(entry.name)) continue;
        const ext = path.extname(entry.name);
        if (SKIP_EXTS.has(ext) || SKIP_EXTS.has(entry.name)) continue;

        const fileAbs = path.join(baseDir, nextRel);
        const data = await fs.readFile(fileAbs);
        zip.file(nextRel.replaceAll("\\", "/"), data);
      }
    }
    return;
  }

  const fileName = path.basename(absPath);
  if (SKIP_FILE_NAMES.has(fileName)) return;
  const ext = path.extname(fileName);
  if (SKIP_EXTS.has(ext) || SKIP_EXTS.has(fileName)) return;

  const data = await fs.readFile(absPath);
  zip.file(relPath.replaceAll("\\", "/"), data);
}

function safeTag(value: string) {
  const trimmed = String(value || "").trim();
  if (!trimmed) return "stable";
  return trimmed.replace(/[^a-zA-Z0-9._-]+/g, "-").slice(0, 60) || "stable";
}

async function requireAdmin(req: NextRequest) {
  const authHeader = req.headers.get("authorization") || "";
  const token = authHeader.startsWith("Bearer ")
    ? authHeader.slice("Bearer ".length).trim()
    : "";

  if (!token) {
    return { ok: false as const, message: "인증 토큰이 없습니다." };
  }

  const supabaseUrl = getEnv("NEXT_PUBLIC_SUPABASE_URL");
  const supabaseAnonKey = getEnv("NEXT_PUBLIC_SUPABASE_ANON_KEY");
  const serviceRoleKey = getEnv("SUPABASE_SERVICE_ROLE_KEY");

  const authClient = createClient(supabaseUrl, supabaseAnonKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  const { data: authData, error: authError } = await authClient.auth.getUser(token);

  if (authError || !authData.user) {
    return { ok: false as const, message: "로그인 세션을 확인하지 못했습니다." };
  }

  const adminClient = createClient(supabaseUrl, serviceRoleKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  const { data: profileRow, error: profileError } = await adminClient
    .from("profiles")
    .select("is_admin, email")
    .eq("id", authData.user.id)
    .maybeSingle();

  if (profileError) {
    return { ok: false as const, message: "관리자 권한을 확인하지 못했습니다." };
  }

  if (!profileRow?.is_admin) {
    return { ok: false as const, message: "관리자만 백업을 만들 수 있습니다." };
  }

  return {
    ok: true as const,
    userId: authData.user.id,
    email: String(profileRow.email || authData.user.email || ""),
  };
}

export async function POST(req: NextRequest) {
  try {
    const admin = await requireAdmin(req);
    if (!admin.ok) {
      return NextResponse.json({ error: admin.message }, { status: 403 });
    }

    const body = await req.json().catch(() => ({}));
    const tag = safeTag(body?.tag || "stable");

    const projectRoot = process.cwd();
    const zip = new JSZip();

    for (const relPath of INCLUDE_PATHS) {
      const target = path.join(projectRoot, relPath);
      if (!(await exists(target))) continue;
      await addPathToZip(zip, projectRoot, relPath);
    }

    zip.file(
      "backup-info.json",
      JSON.stringify(
        {
          created_at: new Date().toISOString(),
          tag,
          include_paths: INCLUDE_PATHS,
          requested_by: admin.email || admin.userId,
          note: "Generated by /api/admin/backup",
        },
        null,
        2
      )
    );

    const archive = await zip.generateAsync({
      type: "nodebuffer",
      compression: "DEFLATE",
      compressionOptions: { level: 6 },
    });

    const filename = `hotena_backup_${tag}_${new Date()
      .toISOString()
      .slice(0, 10)}.zip`;

    return new NextResponse(archive, {
      status: 200,
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${filename}"`,
        "Cache-Control": "no-store",
      },
    });
  } catch (error) {
    console.error("[admin-backup] failed:", error);
    return NextResponse.json(
      { error: "백업 ZIP 생성 중 오류가 발생했습니다." },
      { status: 500 }
    );
  }
}
